name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths:
      - cpp/**
  pull_request:
    branches: [ "main" ]
    paths:
      - cpp/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest
      run: sudo apt-get install libgtest-dev
    - uses: actions/checkout@v4
    - name: build project
      run: make
    - name: run with sample input
      working-directory: build
      run: ./pfd
    - name: run unit tests
      run: make gtest
